networks:
  default:
    driver: bridge
    name: roboshop
    # external: true

services:
  mongodb:
    image: vidya07422/mongodb:v1
    container_name: mongodb
  catalogue:
    image: vidya07422/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7
    container_name: redis
  user:
    image: vidya07422/user:v1
    container_name: user
    environment: 
      MONGO: true
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://mongodb:27017/users
    depends_on:
    - redis
    - mongodb
  cart: 
    image: vidya07422/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
    - redis
    - catalogue
  mysql: 
    image: vidya07422/mysql:v1
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: RoboShop@1
  shipping:
    image: vidya07422/shipping:v1
    container_name: shipping
    environment:
      CART_ENDPOINT: cart:8080
      DB_HOST: mysql
    depends_on: 
    - cart
    - mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  payment: 
    image: vidya07422/payment:v1
    container_name: payment
    environment: 
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on: 
    - cart
    - user
    - rabbitmq
  frontend: 
    image: vidya07422/frontend:v1
    container_name: frontend
    ports: 
    - "80:80"
    depends_on: 
    - cart
    - shipping
    - catalogue
    - payment
    - user